name: Plugin Validator

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
    - 'Plugins/**'
  pull_request:
    paths: 
    - 'Plugins/**'
  
jobs:
  xml-check:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'auto-')"

    steps:
    - name: Checkout Plugin Hub
      uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Validate
      run: 'python test.py Plugins/'
